Workshop1


In [ ]:
#Problem 1 - Array Creation
#Q1
import numpy as np
a = np.empty((2,2))
print (a)

[[0. 0.]
 [0. 0.]]


In [ ]:
#2
import numpy as np
a= np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3
import numpy as np
a = np.full((2, 3), 5)
print(a)

[[5 5 5]
 [5 5 5]]


In [ ]:
#4
import numpy as np
a = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(a)
print(zeros_like_array)

[[0 0]
 [0 0]]


In [ ]:
#5
import numpy as np
a = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(a)
print(ones_like_array)

[[1 1]
 [1 1]]


In [ ]:
#6
import numpy as np
new_list =[1, 2, 3, 4]
converted_array = np.array(new_list)
print(converted_array)

[1 2 3 4]


In [ ]:
#Problem 2:Array Manipulation : Numerical Rangers and Array Indexing
#1
import numpy as np
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2
import numpy as np
m = np.arange(9).reshape(3, 3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3
import numpy as np
identity_m = np.eye(3)
print(identity_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
import numpy as np
a = np.random.random(30)
mean = a.mean()
print(a, mean)

[0.86211263 0.49801528 0.06559417 0.64784565 0.71278097 0.82384632
 0.78181266 0.57254236 0.31003167 0.65714861 0.48578479 0.79669783
 0.22851827 0.41472309 0.53102866 0.57904585 0.82119451 0.141027
 0.77795686 0.60536911 0.94284661 0.94210576 0.24057658 0.14732062
 0.33839329 0.20343313 0.07960012 0.17943465 0.88183011 0.61589047] 0.5294835874347649


In [ ]:
#5
import numpy as np
a = np.random.random((10, 10))
a_min = a.min()
a_max = a.max()
print("Minimum Value:", a_min, "\nMaximum Value:", a_max)

Minimum Value: 0.011331172194422146 
Maximum Value: 0.9835009835384737


In [ ]:
#6
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
import numpy as np
a = np.array([1, 2, 0, 0, 4, 0])
reversed_a = a[::-1]

print("Reversed array:", reversed_a)


Reversed array: [0 4 0 0 2 1]


In [ ]:
#8
import numpy as np
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
#Problem-3:Array Operations
#1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_a = x + y
add_a1 = v + w
print("Addition of X and Y:", add_a, "\nAddition of V and W:", add_a1)

Addition of X and Y: [[ 6  8]
 [10 13]] 
Addition of V and W: [20 22]


In [ ]:
#2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sub_a = x - y
sub_a1 = v - w
print("Subtraction of X and Y:", sub_a, "\nSubtraction of V and W:", sub_a1)

Subtraction of X and Y: [[-4 -4]
 [-4 -3]] 
Subtraction of V and W: [-2 -2]


In [ ]:
#3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
mul_a = x * 9
print(mul_a)

[[ 9 18]
 [27 45]]


In [ ]:
#4
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square_aX = x**2
square_aY = y**2
square_aV = v**2
square_aW = w**2
print(square_aX, "\n",square_aY,"\n",square_aV,"\n",square_aW)

[[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]] 
 [ 81 100] 
 [121 144]


In [ ]:
#5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)
print("Dot Product of V and W:",dot_product_vw, "\nDot Product of X and V: ",dot_product_xv,"\nDot Product of X and Y:",dot_product_xy)

Dot Product of V and W: 219 
Dot Product of X and V:  [29 77] 
Dot Product of X and Y: [[19 22]
 [50 58]]


In [ ]:
#6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.vstack((v, w)).T
print(concat_xy_rows)
print(concat_vw_columns)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [ ]:
#7
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print(concat_xv_error)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
#Problem-4: Matrix Operations
#1
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("\nA.A^-1:\n", I)


A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True


In [ ]:
#3
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
AB_transpose = AB.transpose()
B_transpose = B.transpose()
A_transpose = A.transpose()
BT_AT = np.dot(B_transpose, A_transpose)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))


(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ: True


In [ ]:
#Linear Equation
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])


# Using inverse method
X = np.dot(np.linalg.inv(A), B)
print("\nSolution using inverse method:\n", X)


# Using np.linalg.solve
X_solve = np.linalg.solve(A,B)
print("\nSolution using np.linalg.solve:\n", X_solve)


Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


In [ ]:
import numpy as np
import time


# 1. Element-wise Addition
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)


start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
print("List element-wise addition time:", end_time - start_time)

start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
print("Numpy element-wise addition time:", end_time - start_time)

List element-wise addition time: 0.06446480751037598
Numpy element-wise addition time: 0.004144430160522461


In [ ]:
# 2. Element-wise Multiplication
start_time = time.time()
list_mult = [x * y for x, y in zip(list1, list2)]
end_time = time.time()
print("List element-wise multiplication time:", end_time - start_time)

start_time = time.time()
array_mult = array1 * array2
end_time = time.time()
print("Numpy element-wise multiplication time:", end_time - start_time)

List element-wise multiplication time: 0.24567842483520508
Numpy element-wise multiplication time: 0.014245271682739258


In [ ]:
# 3. Dot Product
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)
start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
end_time = time.time()
print("List dot product time:", end_time - start_time)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Numpy dot product time:", end_time - start_time)

List dot product time: 0.0829930305480957
Numpy dot product time: 0.001756429672241211


In [ ]:
import numpy as np
import time

# Use smaller size for Python lists
size_list = 100  # Python lists only
size_np = 1000   # NumPy arrays

# Python list matrices
matrix1 = [[j for j in range(size_list)] for i in range(size_list)]
matrix2 = [[j for j in range(size_list)] for i in range(size_list)]

start = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size_list))
                  for j in range(size_list)]
                  for i in range(size_list)]
end = time.time()
print("Python list 100x100 matrix multiplication time:", end - start)

# NumPy arrays
matrix1_np = np.arange(size_np**2).reshape(size_np, size_np)
matrix2_np = np.arange(size_np**2).reshape(size_np, size_np)

start = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end = time.time()
print("NumPy 1000x1000 matrix multiplication time:", end - start)


Python list 100x100 matrix multiplication time: 0.09589886665344238
NumPy 1000x1000 matrix multiplication time: 2.635279893875122
